/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
* Specifies the datatype of a MAVLink parameter.
*/
public class MAV_PATTERN {
   public static final int MAV_PATTERN_AB = 0; /* STRAIGHT_AB | */
   public static final int MAV_PATTERN_LINE_APLUS = 1; /* LINE_APLUS | */
   public static final int MAV_PATTERN_CURVE_IDENTICAL = 2; /* CURVE_IDENTICAL | */
   public static final int MAV_PATTERN_PIVOT = 3; /* PIVOT | */
   public static final int MAV_PATTERN_HEADLAND = 4; /* HEADLAND | */
   public static final int MAV_PATTERN_FREEFORM = 5; /* FREEFORM | */
   public static final int MAV_PATTERN_ENUM_END = 6; /*  | */
}
            