/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
* auto stop case.
*/
public class MAV_NAV_STOP_CASE {
   public static final int MAV_STOP_USER = 0; /* user action | */
   public static final int MAV_STOP_OUT = 1; /* out line | */
   public static final int MAV_STOP_END = 2; /* end | */
   public static final int MAV_STOP_CONTROL = 3; /* from control | */
   public static final int MAV_STOP_LINE_ERR = 4; /* direct err | */
   public static final int MAV_STOP_OUT_CONTROL = 5; /* out of control | */
   public static final int MAV_NAV_STOP_CASE_ENUM_END = 6; /*  | */
}
            