/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 *
 */
public class NOTIFICATION_TYPE {
    public static final int AUTOPILOT_STOP_CAUSE_STEERING_WHEEL = 0; //打方向盘干预自动驾驶
    public static final int AUTOPILOT_STOP_CAUSE_SENSOR_FAULT = 1; //设备连接异常
    public static final int CAUSE_STEERING_WHEEL = 0;//手动干预
    public static final int CAUSE_SENSOR_FAULT_ANGLESENSOR_IS_CONNECTED = 1;//角度传感器未连接
    public static final int CAUSE_SENSOR_FAULT_ANGLESENSOR_IS_NORMAL = 2;//角度传感器数据异常
    public static final int CAUSE_SENSOR_FAULT_GPS_HAVE_DATA = 3;//卫星信号异常
    public static final int CAUSE_SENSOR_FAULT_IMU_HAVE_DATA = 4;//惯性测量无数据
    public static final int CAUSE_SENSOR_FAULT_IMU_IS_NORMAL = 5;//惯性测量数据异常
    public static final int CAUSE_SENSOR_FAULT_YAW_IS_INIT = 6;//方向角错误
    public static final int CAUSE_SENSOR_FAULT_HEARTBEAT = 7;//控制箱检测不到心跳
    public static final int CAUSE_SENSOR_FAULT_GPS_IS_FIXED = 8;//卫星信号异常
    public static final int CAUSE_MOTOR_FAULT_CONNECTED = 9;//电机连接状态异常
    public static final int CAUSE_MOTOR_FAULT_IS_NORMAL = 10;//电机工作状态异常
    public static final int CAUSE_BUTTON = 11;//按钮点击
    public static final int CAUSE_WISE40_FAULT_CONNECTED = 12;  // 履带控制器连接异常
    public static final int CAUSE_WISE40_FAULT_IS_NORMAL = 13;  // 履带控制器工作异常

    public static final int CAUSE_USER_CLICK = 100;//用户点击屏幕
    public static final int CAUSE_USER_PHYSICAL = 101;//用户点击物理按键
    public static final int CAUSE_SENSOR_FAULT_CONTROLL_OUT = 102;//控制箱断开
    public static final int CAUSE_UNKNOWN = 103;//未知原因
    public static final int CAUSE_NONE = -1;//缺省值

    public static final int REACHED_THE_LINE = 1; /* REACHED_THE_LINE | */
    public static final int NOTIFICATION_TYPE_ENUM_END = 2; /*  | */
}
            