/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE MESSAGE_ACK PACKING
package com.MAVLink.MAVLink.common;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
* Report status of a data.
*/
public class msg_message_ack extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_MESSAGE_ACK = 156;
    public static final int MAVLINK_MSG_LENGTH = 9;
    private static final long serialVersionUID = MAVLINK_MSG_ID_MESSAGE_ACK;


      
    /**
    * from message of index field
    */
    public long index;
      
    /**
    * message id about request
    */
    public short req_message;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_MESSAGE_ACK;
              
        packet.payload.putUnsignedLong(index);
              
        packet.payload.putUnsignedByte(req_message);
        
        return packet;
    }

    /**
    * Decode a message_ack message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.index = payload.getUnsignedLong();
              
        this.req_message = payload.getUnsignedByte();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_message_ack(){
        msgid = MAVLINK_MSG_ID_MESSAGE_ACK;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_message_ack(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_MESSAGE_ACK;
        unpack(mavLinkPacket.payload);        
    }

        
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_MESSAGE_ACK -"+" index:"+index+" req_message:"+req_message+"";
    }
}
        