/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE STEER_INFO PACKING
package com.MAVLink.MAVLink.common;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
* Steering infomation.
*/
public class msg_steer_info extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_STEER_INFO = 300;
    public static final int MAVLINK_MSG_LENGTH = 16;
    private static final long serialVersionUID = MAVLINK_MSG_ID_STEER_INFO;


      
    /**
    * Timestamp (microseconds since UNIX epoch or microseconds since system boot)
    */
    public long time_usec;
      
    /**
    * set lateral acceleration 
    */
    public short set_acc;
      
    /**
    * Servo output 1 value, in microseconds
    */
    public int servo_pwm;
      
    /**
    * wheel angel
    */
    public short wheel_angel;
      
    /**
    * Y acceleration (raw)
    */
    public short y_acc;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_STEER_INFO;
              
        packet.payload.putUnsignedLong(time_usec);
              
        packet.payload.putShort(set_acc);
              
        packet.payload.putUnsignedShort(servo_pwm);
              
        packet.payload.putShort(wheel_angel);
              
        packet.payload.putShort(y_acc);
        
        return packet;
    }

    /**
    * Decode a steer_info message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.time_usec = payload.getUnsignedLong();
              
        this.set_acc = payload.getShort();
              
        this.servo_pwm = payload.getUnsignedShort();
              
        this.wheel_angel = payload.getShort();
              
        this.y_acc = payload.getShort();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_steer_info(){
        msgid = MAVLINK_MSG_ID_STEER_INFO;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_steer_info(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_STEER_INFO;
        unpack(mavLinkPacket.payload);        
    }

              
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_STEER_INFO -"+" time_usec:"+time_usec+" set_acc:"+set_acc+" servo_pwm:"+servo_pwm+" wheel_angel:"+wheel_angel+" y_acc:"+y_acc+"";
    }
}
        