/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE IMU_DETAIL PACKING
package com.MAVLink.MAVLink.common;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
* IMU DETAIL.
*/
public class msg_imu_detail extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_IMU_DETAIL = 10;
    public static final int MAVLINK_MSG_LENGTH = 60;
    private static final long serialVersionUID = MAVLINK_MSG_ID_IMU_DETAIL;


      
    /**
    * reserved.
    */
    public long time;
      
    /**
    * reserved.
    */
    public float gyro_x;
      
    /**
    * reserved.
    */
    public float gyro_y;
      
    /**
    * reserved.
    */
    public float gyro_z;
      
    /**
    * reserved.
    */
    public float accel_x;
      
    /**
    * reserved.
    */
    public float accel_y;
      
    /**
    * reserved.
    */
    public float accel_z;
      
    /**
    * reserved.
    */
    public float mag_x;
      
    /**
    * reserved.
    */
    public float mag_y;
      
    /**
    * reserved.
    */
    public float mag_z;
      
    /**
    * reserved.
    */
    public float fwa_rate;
      
    /**
    * reserved.
    */
    public float fwa_voltage;
      
    /**
    * reserved.
    */
    public float fwa_angle_p;
      
    /**
    * reserved.
    */
    public float fwa_angle_g;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_IMU_DETAIL;
              
        packet.payload.putUnsignedLong(time);
              
        packet.payload.putFloat(gyro_x);
              
        packet.payload.putFloat(gyro_y);
              
        packet.payload.putFloat(gyro_z);
              
        packet.payload.putFloat(accel_x);
              
        packet.payload.putFloat(accel_y);
              
        packet.payload.putFloat(accel_z);
              
        packet.payload.putFloat(mag_x);
              
        packet.payload.putFloat(mag_y);
              
        packet.payload.putFloat(mag_z);
              
        packet.payload.putFloat(fwa_rate);
              
        packet.payload.putFloat(fwa_voltage);
              
        packet.payload.putFloat(fwa_angle_p);
              
        packet.payload.putFloat(fwa_angle_g);
        
        return packet;
    }

    /**
    * Decode a imu_detail message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.time = payload.getUnsignedLong();
              
        this.gyro_x = payload.getFloat();
              
        this.gyro_y = payload.getFloat();
              
        this.gyro_z = payload.getFloat();
              
        this.accel_x = payload.getFloat();
              
        this.accel_y = payload.getFloat();
              
        this.accel_z = payload.getFloat();
              
        this.mag_x = payload.getFloat();
              
        this.mag_y = payload.getFloat();
              
        this.mag_z = payload.getFloat();
              
        this.fwa_rate = payload.getFloat();
              
        this.fwa_voltage = payload.getFloat();
              
        this.fwa_angle_p = payload.getFloat();
              
        this.fwa_angle_g = payload.getFloat();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_imu_detail(){
        msgid = MAVLINK_MSG_ID_IMU_DETAIL;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_imu_detail(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_IMU_DETAIL;
        unpack(mavLinkPacket.payload);        
    }

                                
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_IMU_DETAIL -"+" time:"+time+" gyro_x:"+gyro_x+" gyro_y:"+gyro_y+" gyro_z:"+gyro_z+" accel_x:"+accel_x+" accel_y:"+accel_y+" accel_z:"+accel_z+" mag_x:"+mag_x+" mag_y:"+mag_y+" mag_z:"+mag_z+" fwa_rate:"+fwa_rate+" fwa_voltage:"+fwa_voltage+" fwa_angle_p:"+fwa_angle_p+" fwa_angle_g:"+fwa_angle_g+"";
    }
}
        