/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE AUTOPILOT_SET_AB_REQ PACKING
package com.MAVLink.MAVLink.common;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
* autopilot req.
*/
public class msg_autopilot_set_ab_req extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_AUTOPILOT_SET_AB_REQ = 13;
    public static final int MAVLINK_MSG_LENGTH = 16;
    private static final long serialVersionUID = MAVLINK_MSG_ID_AUTOPILOT_SET_AB_REQ;


      
    /**
    * a latitude.
    */
    public int a_lat;
      
    /**
    * a longitude.
    */
    public int a_lng;
      
    /**
    * b latitude.
    */
    public int b_lat;
      
    /**
    * b longitude
    */
    public int b_lng;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_AUTOPILOT_SET_AB_REQ;
              
        packet.payload.putInt(a_lat);
              
        packet.payload.putInt(a_lng);
              
        packet.payload.putInt(b_lat);
              
        packet.payload.putInt(b_lng);
        
        return packet;
    }

    /**
    * Decode a autopilot_set_ab_req message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.a_lat = payload.getInt();
              
        this.a_lng = payload.getInt();
              
        this.b_lat = payload.getInt();
              
        this.b_lng = payload.getInt();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_autopilot_set_ab_req(){
        msgid = MAVLINK_MSG_ID_AUTOPILOT_SET_AB_REQ;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_autopilot_set_ab_req(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_AUTOPILOT_SET_AB_REQ;
        unpack(mavLinkPacket.payload);        
    }

            
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_AUTOPILOT_SET_AB_REQ -"+" a_lat:"+a_lat+" a_lng:"+a_lng+" b_lat:"+b_lat+" b_lng:"+b_lng+"";
    }
}
        