/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE GPS_CMD PACKING
package com.MAVLink.MAVLink.common;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
*  
*/
public class msg_gps_cmd extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_GPS_CMD = 94;
    public static final int MAVLINK_MSG_LENGTH = 130;
    private static final long serialVersionUID = MAVLINK_MSG_ID_GPS_CMD;


      
    /**
    *  
    */
    public short gps_index;
      
    /**
    *  
    */
    public short len;
      
    /**
    *  
    */
    public short data[] = new short[128];
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_GPS_CMD;
              
        packet.payload.putUnsignedByte(gps_index);
              
        packet.payload.putUnsignedByte(len);
              
        
        for (int i = 0; i < data.length; i++) {
            packet.payload.putUnsignedByte(data[i]);
        }
                    
        
        return packet;
    }

    /**
    * Decode a gps_cmd message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.gps_index = payload.getUnsignedByte();
              
        this.len = payload.getUnsignedByte();
              
         
        for (int i = 0; i < this.data.length; i++) {
            this.data[i] = payload.getUnsignedByte();
        }
                
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_gps_cmd(){
        msgid = MAVLINK_MSG_ID_GPS_CMD;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_gps_cmd(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_GPS_CMD;
        unpack(mavLinkPacket.payload);        
    }

    public String getResult() {
        int length = len;
        if (length > data.length) {
            length = data.length;
        }
        byte[] bytes = new byte[length];
        for (int i = 0; i < length; i++) {
            bytes[i] = (byte) data[i];
        }
        return new String(bytes);
    }


    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_GPS_CMD -"+" gps_index:"+gps_index+" len:"+len+" data:"+data+"";
    }
}
        
