/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE VEHICLE_PARAM_DATA PACKING
package com.MAVLink.MAVLink.common;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
* Vehicle params.
*/
public class msg_vehicle_param_data extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_VEHICLE_PARAM_DATA = 152;
    public static final int MAVLINK_MSG_LENGTH = 44;
    private static final long serialVersionUID = MAVLINK_MSG_ID_VEHICLE_PARAM_DATA;


      
    /**
    * device id
    */
    public long deviceid;
      
    /**
    * message id
    */
    public long index;
      
    /**
    * UNIX time (+8),yyyyMMddHHmmss,sample 2017.5.15 11:00:00, timestamp is 20170515110000
    */
    public long timestamp;
      
    /**
    * The height of the antenna from the horizontal ground, in cm
    */
    public float height;
      
    /**
    * To the front axle to offset, the horizontal distance of the antenna to the front axle, in cm
    */
    public float offset_front;
      
    /**
    * To the rear axle offset, the horizontal distance from the antenna to the rear axle, in cm
    */
    public float offset_rear;
      
    /**
    * To the left of the rear axle offset, the horizontal distance from the antenna to the left side of the rear axle, in cm
    */
    public float offset_left;
      
    /**
    * To the right side of the rear axle offset, the horizontal distance from the antenna to the right side of the rear axle, in cm
    */
    public float offset_right;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_VEHICLE_PARAM_DATA;
              
        packet.payload.putUnsignedLong(deviceid);
              
        packet.payload.putUnsignedLong(index);
              
        packet.payload.putUnsignedLong(timestamp);
              
        packet.payload.putFloat(height);
              
        packet.payload.putFloat(offset_front);
              
        packet.payload.putFloat(offset_rear);
              
        packet.payload.putFloat(offset_left);
              
        packet.payload.putFloat(offset_right);
        
        return packet;
    }

    /**
    * Decode a vehicle_param_data message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.deviceid = payload.getUnsignedLong();
              
        this.index = payload.getUnsignedLong();
              
        this.timestamp = payload.getUnsignedLong();
              
        this.height = payload.getFloat();
              
        this.offset_front = payload.getFloat();
              
        this.offset_rear = payload.getFloat();
              
        this.offset_left = payload.getFloat();
              
        this.offset_right = payload.getFloat();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_vehicle_param_data(){
        msgid = MAVLINK_MSG_ID_VEHICLE_PARAM_DATA;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_vehicle_param_data(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_VEHICLE_PARAM_DATA;
        unpack(mavLinkPacket.payload);        
    }

                    
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_VEHICLE_PARAM_DATA -"+" deviceid:"+deviceid+" index:"+index+" timestamp:"+timestamp+" height:"+height+" offset_front:"+offset_front+" offset_rear:"+offset_rear+" offset_left:"+offset_left+" offset_right:"+offset_right+"";
    }
}
        